name: Build, Publish and Release

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: infinit3hq/devcents

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create tag
        id: create_tag
        run: |
          TAG="v$(date +'%Y.%m.%d')-${GITHUB_SHA::7}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%s)
          gh release create "${{ steps.create_tag.outputs.tag }}" \
            --title "$COMMIT_MSG" \
            --generate-notes \
            --target "${{ github.sha }}"
